<?php
declare(strict_types=1);

function handle_export(): void
{
    $user = require_role(['admin', 'staff']);
    $type = preg_replace('/[^a-z]/', '', (string) ($_GET['type'] ?? 'appointment')) ?: 'appointment';
    $payload = report_payload($type);

    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="detabot-' . $type . '-report.csv"');

    $out = fopen('php://output', 'w');
    fputcsv($out, [$payload['title']]);
    fputcsv($out, ['Generated by', $user['username'], 'Generated at', date('Y-m-d H:i:s')]);
    fputcsv($out, []);
    fputcsv($out, ['Summary']);
    foreach ($payload['summary'] as $label => $value) {
        fputcsv($out, [$label, $value]);
    }
    fputcsv($out, []);

    if (!empty($payload['rows'])) {
        fputcsv($out, array_keys($payload['rows'][0]));
        foreach ($payload['rows'] as $row) {
            fputcsv($out, $row);
        }
    }

    log_activity('export_report', 'Exported ' . $type . ' report', (int) $user['userID']);
    exit;
}

function handle_appointment_slots(): void
{
    require_login();

    $date = normalize_appointment_date($_GET['date'] ?? null);
    $clinicID = (int) (clinic()['clinicID'] ?? 1);

    json_response([
        'ok' => true,
        'date' => $date,
        'slots' => appointment_slot_list($date, $clinicID),
    ]);
}

function handle_post(): void
{
    $action = (string) ($_POST['action'] ?? '');

    if ($action === 'register') {
        $name   = trim((string) ($_POST['username'] ?? ''));
        $email  = strtolower(trim((string) ($_POST['userEmail'] ?? '')));
        $phone  = trim((string) ($_POST['userPhone'] ?? ''));
        $password = (string) ($_POST['userPassword'] ?? '');
        $age    = (int) ($_POST['userAge'] ?? 0);
        $gender = (string) ($_POST['userGender'] ?? '');
        $chronicProblems = normalize_chronic_health_problems($_POST['chronicHealthProblems'] ?? []);
        $chronicProblemDetail = implode(', ', $chronicProblems);

        if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL) || $phone === '' || strlen($password) < 6) {
            flash('danger', 'Please complete the registration form. Password must be at least 6 characters.');
            redirect_to('index.php?view=register');
        }

        if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL) || $phone === '' || strlen($password) < 6) {
            flash('danger', 'Please complete the registration form. Password must be at least 6 characters.');
            redirect_to('index.php?view=register');
        }

        if ($age < 1 || $age > 120) {
            flash('danger', 'Please enter a valid age (1–120).');
            redirect_to('index.php?view=register');
        }

        if (!in_array($gender, ['male', 'female'], true)) {
            flash('danger', 'Please select a gender.');
            redirect_to('index.php?view=register');
        }

        if (db_one('SELECT userID FROM tbl_user WHERE userEmail = ?', [$email])) {
            flash('danger', 'An account with this email already exists.');
            redirect_to('index.php?view=register');
        }
        $role = 'patient';
        if (str_ends_with($email, '@dentalputra.com')) {
            if (str_starts_with($email, 'admin')) {
                $role = 'admin';
            } else {
                $role = 'staff';
            }
        }

        db_execute(
            'INSERT INTO tbl_user (username, userEmail, userPassword, userPhone, userAge, userGender, userChronicHealthProblems, userRole, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [$name, $email, password_hash($password, PASSWORD_DEFAULT), $phone, $age, $gender, $chronicProblemDetail, $role, 'active']
        );

        $_SESSION['userID'] = (int) db()->lastInsertId();
        $accountType = $role === 'patient' ? 'patient' : $role;
        log_activity('register', 'New ' . $accountType . ' account created');
        flash('success', 'Welcome to Detabot. Your ' . $accountType . ' account is ready.');
        redirect_to(page_url('dashboard'));
    }

    if ($action === 'reset_password') {
        $email = strtolower(trim((string) ($_POST['userEmail'] ?? '')));
        $password = (string) ($_POST['userPassword'] ?? '');

        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            flash('danger', 'Please enter a valid registered email address.');
            redirect_to('index.php?view=forgot');
        }

        if (strlen($password) < 6) {
            flash('danger', 'Password must be at least 6 characters.');
            redirect_to('index.php?view=forgot&email=' . urlencode($email));
        }

        $user = db_one('SELECT * FROM tbl_user WHERE userEmail = ? AND status = ?', [$email, 'active']);
        if (!$user) {
            flash('danger', 'No active account found for that email.');
            redirect_to('index.php?view=forgot&email=' . urlencode($email));
        }

        db_execute(
            'UPDATE tbl_user SET userPassword = ? WHERE userID = ?',
            [password_hash($password, PASSWORD_DEFAULT), (int) $user['userID']]
        );
        log_activity('reset_password', 'Password reset from forgot password form', (int) $user['userID']);
        flash('success', 'Password reset successfully. Please sign in with your new password.');
        redirect_to('index.php');
    }

    if ($action === 'login') {
        $email = strtolower(trim((string) ($_POST['userEmail'] ?? '')));
        $password = (string) ($_POST['userPassword'] ?? '');
        $user = db_one('SELECT * FROM tbl_user WHERE userEmail = ? AND status = ?', [$email, 'active']);

        if (!$user || !password_verify($password, $user['userPassword'])) {
            flash('danger', 'Invalid email or password.');
            redirect_to('index.php');
        }

        $_SESSION['userID'] = (int) $user['userID'];
        log_activity('login', 'User signed in', (int) $user['userID']);
        flash('success', 'Signed in successfully.');
        redirect_to(page_url('dashboard'));
    }

    if ($action === 'logout') {
        if (isset($_SESSION['userID'])) {
            log_activity('logout', 'User signed out', (int) $_SESSION['userID']);
        }
        session_destroy();
        redirect_to('index.php');
    }

    $user = require_login();

    if ($action === 'book_appointment') {
        $clinic = clinic();
        $clinicID = (int) ($clinic['clinicID'] ?? 1);
        $patientID = has_role($user, ['admin', 'staff'])
            ? (int) ($_POST['userID'] ?? $user['userID'])
            : (int) $user['userID'];
        $date = (string) ($_POST['appointmentDate'] ?? '');
        $time = substr((string) ($_POST['appointmentTime'] ?? ''), 0, 5);
        $service = trim((string) ($_POST['serviceType'] ?? ''));
        $duration = service_duration_minutes($service);
        $notes = trim((string) ($_POST['notes'] ?? ''));
        $allowedDentists = [
            'Dr. Muhammad Firdaus',
            'Dr. Siti Zafirah',
            'Dr. Alia Suhana',
        ];
        $dentistName = trim((string) ($_POST['dentistName'] ?? ''));
        $paymentLabels = [
            'counter' => 'Pay at clinic counter',
            'qr' => 'QR Bank / E-wallet',
        ];
        $paymentMethod = (string) ($_POST['paymentMethod'] ?? 'counter');
        $qrPaymentLabels = [
            'tng' => "Touch 'n Go",
            'fpx' => 'FPX',
        ];
        $qrPaymentType = (string) ($_POST['qrPaymentType'] ?? '');
        $patientAge = (int) ($_POST['patientAge'] ?? 0);
        $healthProblemCategory = (string) ($_POST['healthProblemCategory'] ?? 'none');
        $healthProblemCategory = in_array($healthProblemCategory, ['none', 'common'], true)
            ? $healthProblemCategory
            : 'none';
        $postedProblems = $healthProblemCategory === 'common'
            ? ($_POST['commonHealthProblems'] ?? [])
            : [];
        $postedProblems = is_array($postedProblems) ? $postedProblems : [];
        $allowedProblems = $healthProblemCategory === 'common'
            ? common_health_problem_options()
            : [];
        $healthProblems = array_values(array_intersect(
            array_map('strval', $postedProblems),
            $allowedProblems
        ));
        $healthProblemDetail = $healthProblemCategory === 'none' ? '' : implode(', ', $healthProblems);
        $today = date('Y-m-d');

        if ($patientID <= 0 || $date < $today || !in_array($time, build_time_slots(), true) || $service === '') {
            flash('danger', 'Please choose a valid patient, date, time, and service.');
            redirect_to(page_url('appointments'));
        }

        if (!in_array($dentistName, $allowedDentists, true)) {
            flash('danger', 'Please choose a valid dentist.');
            redirect_to(page_url('appointments', ['date' => $date]));
        }

        if (!isset($paymentLabels[$paymentMethod])) {
            flash('danger', 'Please choose a valid payment method.');
            redirect_to(page_url('appointments', ['date' => $date]));
        }

        if ($paymentMethod === 'qr' && !isset($qrPaymentLabels[$qrPaymentType])) {
            flash('danger', "Please choose Touch 'n Go or FPX payment.");
            redirect_to(page_url('appointments', ['date' => $date]));
        }

        $receiptStored = '';
        if ($paymentMethod === 'qr') {
            $receiptFile = $_FILES['paymentReceipt'] ?? null;
            if (!is_array($receiptFile) || (int) ($receiptFile['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
                flash('danger', 'Please upload your payment receipt before submitting.');
                redirect_to(page_url('appointments', ['date' => $date]));
            }

            $allowedReceiptMimes = ['image/jpeg' => 'jpg', 'image/png' => 'png', 'image/webp' => 'webp', 'application/pdf' => 'pdf'];
            $maxReceiptBytes = 5 * 1024 * 1024;
            $receiptTmp = (string) ($receiptFile['tmp_name'] ?? '');
            $receiptSize = (int) ($receiptFile['size'] ?? 0);

            if ($receiptSize > $maxReceiptBytes || $receiptTmp === '') {
                flash('danger', 'Receipt file must be under 5 MB.');
                redirect_to(page_url('appointments', ['date' => $date]));
            }

            $receiptMime = function_exists('mime_content_type') ? (string) mime_content_type($receiptTmp) : (string) ($receiptFile['type'] ?? '');
            if (!isset($allowedReceiptMimes[$receiptMime])) {
                flash('danger', 'Only JPG, PNG, WEBP or PDF receipts are allowed.');
                redirect_to(page_url('appointments', ['date' => $date]));
            }

            $receiptDir = payment_receipt_upload_dir();
            $receiptStored = 'receipt_' . date('Ymd_His') . '_' . bin2hex(random_bytes(6)) . '.' . $allowedReceiptMimes[$receiptMime];
            if (!move_uploaded_file($receiptTmp, $receiptDir . '/' . $receiptStored)) {
                flash('danger', 'Failed to save receipt. Please try again.');
                redirect_to(page_url('appointments', ['date' => $date]));
            }
        }

        if ($patientAge < 1 || $patientAge > 120) {
            flash('danger', 'Please enter a valid patient age.');
            redirect_to(page_url('appointments', ['date' => $date]));
        }

        if ($healthProblemCategory !== 'none' && $healthProblemDetail === '') {
            flash('danger', 'Please choose at least one health problem.');
            redirect_to(page_url('appointments', ['date' => $date]));
        }

        if (!appointment_meets_minimum_notice($date, $time)) {
            flash('danger', 'Please choose another available appointment time.');
            redirect_to(page_url('appointments', ['date' => $date]));
        }

        if (appointment_conflict($clinicID, $date, $time)) {
            flash('danger', 'That appointment slot is already taken. Please choose another time.');
            redirect_to(page_url('appointments', ['date' => $date]));
        }

        $paymentNote = 'Payment method: ' . $paymentLabels[$paymentMethod];
        if ($paymentMethod === 'qr') {
            $paymentNote .= ' - ' . $qrPaymentLabels[$qrPaymentType];
        }
        $dentistNote = 'Dentist: ' . $dentistName;
        $bookingNotes = [$dentistNote, $paymentNote];
        $notes = $notes === '' ? implode("\n", $bookingNotes) : $notes . "\n" . implode("\n", $bookingNotes);

        db_execute(
            'INSERT INTO tbl_appointment (userID, clinicID, appointmentDate, appointmentTime, serviceType, duration, status, patientAge, healthProblemCategory, healthProblemDetail, notes, paymentReceipt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [$patientID, $clinicID, $date, $time . ':00', $service, $duration, 'pending', $patientAge, $healthProblemCategory, $healthProblemDetail, $notes, $receiptStored ?: null]
        );

        $newAppointmentID = (int) db()->lastInsertId();
        $emailPaymentLabel = $paymentLabels[$paymentMethod];
        if ($paymentMethod === 'qr' && isset($qrPaymentLabels[$qrPaymentType])) {
            $emailPaymentLabel .= ' (' . $qrPaymentLabels[$qrPaymentType] . ')';
        }
        $patient = $patientID === (int) $user['userID']
            ? $user
            : db_one('SELECT userID, username, userEmail FROM tbl_user WHERE userID = ?', [$patientID]);
        if ($patient) {
            send_appointment_receipt($patient, $newAppointmentID, $date, $time, $service, $dentistName, $emailPaymentLabel, $duration);
        }

        flash('success', 'Appointment request submitted. We will review and confirm your slot soon.');
        redirect_to(page_url('appointments'));
    }

    if ($action === 'save_user') {
        require_role('admin');
        $userID   = (int) ($_POST['userID'] ?? 0);
        $name     = trim((string) ($_POST['username'] ?? ''));
        $email    = strtolower(trim((string) ($_POST['userEmail'] ?? '')));
        $phone    = trim((string) ($_POST['userPhone'] ?? ''));
        $age      = (int) ($_POST['userAge'] ?? 0);
        $role     = (string) ($_POST['userRole'] ?? 'patient');
        $status   = (string) ($_POST['status'] ?? 'active');
        $password = (string) ($_POST['userPassword'] ?? '');

        if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL) || $phone === '') {
            flash('danger', 'Please complete all required fields.');
            redirect_to(page_url('users'));
        }

        if (in_array($role, ['staff', 'admin'], true) && !str_ends_with($email, '@dentalputra.com')) {
            flash('danger', 'Staff and Admin accounts must use an email ending with @dentalputra.com.');
            redirect_to(page_url('users'));
        }

        $existing = db_one('SELECT userID FROM tbl_user WHERE userEmail = ? AND userID != ?', [$email, $userID]);
        if ($existing) {
            flash('danger', 'Another account already uses that email.');
            redirect_to(page_url('users'));
        }

        if ($userID > 0) {
            if ($password !== '') {
                db_execute(
                    'UPDATE tbl_user SET username = ?, userEmail = ?, userPhone = ?, userAge = ?, userRole = ?, status = ?, userPassword = ? WHERE userID = ?',
                    [$name, $email, $phone, $age, $role, $status, password_hash($password, PASSWORD_DEFAULT), $userID]
                );
            } else {
                db_execute(
                    'UPDATE tbl_user SET username = ?, userEmail = ?, userPhone = ?, userAge = ?, userRole = ?, status = ? WHERE userID = ?',
                    [$name, $email, $phone, $age, $role, $status, $userID]
                );
            }
            flash('success', 'User account updated.');
            log_activity('update_user', 'Updated user #' . $userID);
        } else {
            if (strlen($password) < 6) {
                flash('danger', 'Password must be at least 6 characters for new users.');
                redirect_to(page_url('users'));
            }
            db_execute(
                'INSERT INTO tbl_user (username, userEmail, userPassword, userPhone, userAge, userRole, status) VALUES (?, ?, ?, ?, ?, ?, ?)',
                [$name, $email, password_hash($password, PASSWORD_DEFAULT), $phone, $age, $role, $status]
            );
            flash('success', 'User account created.');
            log_activity('create_user', 'Created ' . $role . ' account');
        }

        redirect_to(page_url('users'));
    }

    if ($action === 'save_profile') {
        $phone  = trim((string) ($_POST['userPhone'] ?? ''));
        $age    = (int) ($_POST['userAge'] ?? 0);
        $gender = (string) ($_POST['userGender'] ?? '');
        $chronicProblems = normalize_chronic_health_problems($_POST['chronicHealthProblems'] ?? []);
        $chronicProblemDetail = implode(', ', $chronicProblems);
        $allergies = trim((string) ($_POST['userAllergies'] ?? ''));

        if ($phone === '') {
            flash('danger', 'Phone number cannot be empty.');
            redirect_to(page_url('profile'));
        }

        if ($age < 1 || $age > 120) {
            flash('danger', 'Please enter a valid age (1–120).');
            redirect_to(page_url('profile'));
        }

        if (!in_array($gender, ['male', 'female'], true)) {
            flash('danger', 'Please select a gender.');
            redirect_to(page_url('profile'));
        }

        db_execute(
            'UPDATE tbl_user SET userPhone = ?, userAge = ?, userGender = ?, userChronicHealthProblems = ?, userAllergies = ? WHERE userID = ?',
            [$phone, $age, $gender, $chronicProblemDetail, $allergies, (int) $user['userID']]
        );
        log_activity('save_profile', 'Updated own profile');
        flash('success', 'Profile updated successfully.');
        redirect_to(page_url('profile'));
    }

    if ($action === 'change_profile_password') {
        $current  = (string) ($_POST['currentPassword'] ?? '');
        $newPass  = (string) ($_POST['newPassword'] ?? '');
        $confirm  = (string) ($_POST['confirmPassword'] ?? '');

        if (!password_verify($current, (string) $user['userPassword'])) {
            flash('danger', 'Current password is incorrect.');
            redirect_to(page_url('profile'));
        }

        if (strlen($newPass) < 6) {
            flash('danger', 'New password must be at least 6 characters.');
            redirect_to(page_url('profile'));
        }

        if ($newPass !== $confirm) {
            flash('danger', 'Passwords do not match.');
            redirect_to(page_url('profile'));
        }

        db_execute(
            'UPDATE tbl_user SET userPassword = ? WHERE userID = ?',
            [password_hash($newPass, PASSWORD_DEFAULT), (int) $user['userID']]
        );
        log_activity('change_profile_password', 'Changed own password');
        flash('success', 'Password changed successfully.');
        redirect_to(page_url('profile'));
    }

    if ($action === 'delete_account') {
        $password = (string) ($_POST['userPassword'] ?? '');
        if (!password_verify($password, (string) $user['userPassword'])) {
            flash('danger', 'Incorrect password. Account was not deleted.');
            redirect_to(page_url('profile'));
        }
        db_execute('UPDATE tbl_user SET status = ? WHERE userID = ?', ['inactive', (int) $user['userID']]);
        log_activity('delete_account', 'User deactivated own account', (int) $user['userID']);
        session_destroy();
        redirect_to('index.php');
    }

    if ($action === 'upload_avatar') {
        $file = $_FILES['avatar'] ?? null;
        if (!is_array($file) || (int)($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
            flash('danger', 'No valid file uploaded.');
            redirect_to(page_url('profile'));
        }

        $allowedMimes = ['image/jpeg' => 'jpg', 'image/png' => 'png', 'image/webp' => 'webp', 'image/gif' => 'gif'];
        $maxBytes = 2 * 1024 * 1024;
        $tmpName = (string)($file['tmp_name'] ?? '');
        $size = (int)($file['size'] ?? 0);

        if ($size > $maxBytes || $tmpName === '') {
            flash('danger', 'Avatar must be under 2 MB.');
            redirect_to(page_url('profile'));
        }

        $mime = function_exists('mime_content_type') ? (string)mime_content_type($tmpName) : (string)($file['type'] ?? '');
        if (!isset($allowedMimes[$mime])) {
            flash('danger', 'Only JPG, PNG, WEBP or GIF images are allowed.');
            redirect_to(page_url('profile'));
        }

        $avatarDir = user_avatar_dir();
        if (!is_dir($avatarDir)) {
            mkdir($avatarDir, 0775, true);
        }

        // Remove old avatar file if exists
        if (!empty($user['userAvatar'])) {
            @unlink($avatarDir . '/' . $user['userAvatar']);
        }

        $stored = 'avatar_' . $user['userID'] . '_' . bin2hex(random_bytes(6)) . '.' . $allowedMimes[$mime];
        if (!move_uploaded_file($tmpName, $avatarDir . '/' . $stored)) {
            flash('danger', 'Failed to save avatar. Please try again.');
            redirect_to(page_url('profile'));
        }

        db_execute('UPDATE tbl_user SET userAvatar = ? WHERE userID = ?', [$stored, (int)$user['userID']]);
        log_activity('upload_avatar', 'Updated profile picture');
        flash('success', 'Profile picture updated.');
        redirect_to(page_url('profile'));
    }

    if ($action === 'delete_user') {
        require_role('admin');
        $targetID = (int) ($_POST['userID'] ?? 0);
        if ($targetID === (int) $user['userID']) {
            flash('danger', 'You cannot deactivate your own account.');
            redirect_to(page_url('users'));
        }

        db_execute('UPDATE tbl_user SET status = ? WHERE userID = ?', ['inactive', $targetID]);
        log_activity('deactivate_user', 'Deactivated user #' . $targetID);
        flash('success', 'User account deactivated.');
        redirect_to(page_url('users'));
    }

    if ($action === 'generate_report') {
        require_role(['admin', 'staff']);
        $type = preg_replace('/[^a-z]/', '', (string) ($_POST['reportType'] ?? 'appointment')) ?: 'appointment';
        $payload = report_payload($type);
        db_execute(
            'INSERT INTO tbl_report (reportType, generatedBy, reportData, parameters, exportFormat) VALUES (?, ?, ?, ?, ?)',
            [$type, $user['username'], json_encode($payload), json_encode(['generatedAt' => date('c')]), 'screen']
        );

        log_activity('generate_report', 'Generated ' . $type . ' report');
        flash('success', 'Report generated and stored.');
        redirect_to(page_url('reports', ['type' => $type]));
    }

    if ($action === 'redeem_reward') {
        $catalogID = (int) ($_POST['rewardCatalogID'] ?? 0);
        $item = db_one('SELECT * FROM tbl_reward_catalog WHERE rewardCatalogID = ? AND isActive = 1', [$catalogID]);

        if (!$item) {
            flash('danger', 'Reward item is not available.');
            redirect_to(page_url('rewards'));
        }

        $balance = reward_balance((int) $user['userID']);
        $required = (int) $item['pointsRequired'];
        if ($balance < $required) {
            flash('danger', 'Insufficient reward points.');
            redirect_to(page_url('rewards'));
        }

        add_reward_transaction((int) $user['userID'], 0, $required, 'redeemed', 'Redeemed: ' . $item['rewardName']);
        log_activity('redeem_reward', 'Redeemed ' . $item['rewardName']);
        flash('success', 'Reward redeemed. Please show the redemption record at the clinic.');
        redirect_to(page_url('rewards'));
    }

    if ($action === 'save_reward_item') {
        require_role('admin');
        $catalogID = (int) ($_POST['rewardCatalogID'] ?? 0);
        $name = trim((string) ($_POST['rewardName'] ?? ''));
        $points = (int) ($_POST['pointsRequired'] ?? 0);
        $description = trim((string) ($_POST['description'] ?? ''));
        $isActive = isset($_POST['isActive']) ? 1 : 0;

        if ($name === '' || $points <= 0 || $description === '') {
            flash('danger', 'Please complete the reward item.');
            redirect_to(page_url('rewards'));
        }

        if ($catalogID > 0) {
            db_execute(
                'UPDATE tbl_reward_catalog SET rewardName = ?, pointsRequired = ?, description = ?, isActive = ? WHERE rewardCatalogID = ?',
                [$name, $points, $description, $isActive, $catalogID]
            );
            flash('success', 'Reward item updated.');
        } else {
            db_execute(
                'INSERT INTO tbl_reward_catalog (rewardName, pointsRequired, description, isActive) VALUES (?, ?, ?, ?)',
                [$name, $points, $description, $isActive]
            );
            flash('success', 'Reward item added.');
        }

        log_activity('save_reward_item', 'Saved reward catalog item');
        redirect_to(page_url('rewards'));
    }

    if ($action === 'save_health_entry') {
        require_role(['admin', 'staff']);

        $patientID = (int) ($_POST['userID'] ?? 0);
        $appointmentID = (int) ($_POST['appointmentID'] ?? 0) ?: null;
        $title = trim((string) ($_POST['title'] ?? ''));
        $condition = trim((string) ($_POST['condition'] ?? ''));
        $nextTreatment = trim((string) ($_POST['nextTreatment'] ?? ''));
        $nextDate = trim((string) ($_POST['nextDate'] ?? ''));
        $notes = trim((string) ($_POST['notes'] ?? ''));

        if ($patientID <= 0 || $title === '' || $condition === '') {
            flash('danger', 'Patient, title and condition are required.');
            redirect_to(page_url('healthbook'));
        }

        $patient = db_one("SELECT userID FROM tbl_user WHERE userID = ? AND userRole = 'patient' AND status = 'active'", [$patientID]);
        if (!$patient) {
            flash('danger', 'Please choose a valid active patient.');
            redirect_to(page_url('healthbook'));
        }

        if ($appointmentID !== null) {
            $appointment = db_one('SELECT appointmentID FROM tbl_appointment WHERE appointmentID = ? AND userID = ?', [$appointmentID, $patientID]);
            if (!$appointment) {
                $appointmentID = null;
            }
        }

        $chartData = trim((string) ($_POST['chartData'] ?? ''));
        $treatmentPerformed = trim((string) ($_POST['treatmentPerformed'] ?? ''));

        db_execute(
            'INSERT INTO tbl_health_book (userID, appointmentID, createdBy, title, `condition`, nextTreatment, nextDate, notes, chartData, treatmentPerformed) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [$patientID, $appointmentID, (int) $user['userID'], $title, $condition, $nextTreatment ?: null, $nextDate ?: null, $notes ?: null, $chartData ?: null, $treatmentPerformed ?: null]
        );
        $entryID = (int) db()->lastInsertId();

        $uploadFailures = [];
        $files = $_FILES['files'] ?? null;
        if (is_array($files) && isset($files['name']) && is_array($files['name'])) {
            $uploadDir = health_book_upload_dir();
            $allowedMimes = [
                'application/pdf' => 'pdf',
                'image/jpeg' => 'jpg',
                'image/pjpeg' => 'jpg',
                'image/png' => 'png',
                'image/webp' => 'webp',
            ];
            $maxBytes = 5 * 1024 * 1024;

            foreach ($files['name'] as $index => $name) {
                $error = (int) ($files['error'][$index] ?? UPLOAD_ERR_NO_FILE);
                if ($error === UPLOAD_ERR_NO_FILE) {
                    continue;
                }

                $tmpName = (string) ($files['tmp_name'][$index] ?? '');
                $size = (int) ($files['size'][$index] ?? 0);
                if ($error !== UPLOAD_ERR_OK || $tmpName === '' || $size <= 0 || $size > $maxBytes) {
                    $uploadFailures[] = (string) $name;
                    continue;
                }

                $mime = function_exists('mime_content_type') ? (string) mime_content_type($tmpName) : (string) ($files['type'][$index] ?? '');
                if (!isset($allowedMimes[$mime])) {
                    $uploadFailures[] = (string) $name;
                    continue;
                }

                $original = basename(str_replace('\\', '/', (string) $name));
                $stored = bin2hex(random_bytes(16)) . '.' . $allowedMimes[$mime];
                if (!move_uploaded_file($tmpName, $uploadDir . '/' . $stored)) {
                    $uploadFailures[] = $original;
                    continue;
                }

                $fType = trim((string) ($_POST['fileTypes'][$index] ?? 'other'));
                if (!in_array($fType, ['xray', 'cbct', 'intraoral', 'document', 'other'])) {
                    $fType = 'other';
                }

                db_execute(
                    'INSERT INTO tbl_health_book_file (entryID, originalName, storedName, mimeType, fileSize, fileType) VALUES (?, ?, ?, ?, ?, ?)',
                    [$entryID, $original, $stored, $mime, $size, $fType]
                );
            }
        }

        log_activity('save_health_entry', 'Health record entry for patient #' . $patientID);
        if ($uploadFailures) {
            flash('danger', 'Entry saved, but one or more files could not be attached. Use PDF, JPG, PNG, or WEBP under 5 MB.');
        } else {
            flash('success', 'Health record entry saved.');
        }
        redirect_to(page_url('healthbook', ['patient' => $patientID]));
    }

    if ($action === 'delete_health_entry') {
        require_role(['admin', 'staff']);

        $entryID = (int) ($_POST['entryID'] ?? 0);
        $entry = health_book_entry($entryID);
        if ($entry) {
            $uploadDir = health_book_upload_dir();
            foreach (health_book_files($entryID) as $file) {
                @unlink($uploadDir . '/' . $file['storedName']);
            }
            db_execute('DELETE FROM tbl_health_book_file WHERE entryID = ?', [$entryID]);
            db_execute('DELETE FROM tbl_health_book WHERE entryID = ?', [$entryID]);
            log_activity('delete_health_entry', 'Deleted health record entry #' . $entryID);
        }

        flash('success', 'Health record entry deleted.');
        redirect_to(page_url('healthbook', ['patient' => (int) ($entry['userID'] ?? 0)]));
    }

    if ($action === 'delete_health_file') {
        require_role(['admin', 'staff']);

        $fileID = (int) ($_POST['fileID'] ?? 0);
        $file = db_one('SELECT f.*, h.userID FROM tbl_health_book_file f JOIN tbl_health_book h ON h.entryID = f.entryID WHERE f.fileID = ?', [$fileID]);
        if ($file) {
            @unlink(health_book_upload_dir() . '/' . $file['storedName']);
            db_execute('DELETE FROM tbl_health_book_file WHERE fileID = ?', [$fileID]);
            log_activity('delete_health_file', 'Deleted health record file #' . $fileID);
        }

        flash('success', 'File removed.');
        redirect_to(page_url('healthbook', ['patient' => (int) ($file['userID'] ?? 0)]));
    }

    if ($action === 'save_dental_record') {
        require_role(['admin', 'staff']);

        $patientID     = (int)    ($_POST['userID']          ?? 0);
        $apptID        = (int)    ($_POST['appointmentID']   ?? 0) ?: null;
        $toothNumber   = trim((string) ($_POST['toothNumber']    ?? ''));
        $diagnosis     = trim((string) ($_POST['diagnosis']      ?? ''));
        $treatmentDone = trim((string) ($_POST['treatmentDone']  ?? ''));
        $toothCond     = (string) ($_POST['toothCondition']   ?? 'good');
        $nextAction    = trim((string) ($_POST['nextAction']     ?? ''));
        $dentistNotes  = trim((string) ($_POST['dentistNotes']   ?? ''));

        $validConditions = ['good', 'monitor', 'needs_treatment', 'extracted'];
        if (!in_array($toothCond, $validConditions, true)) {
            $toothCond = 'good';
        }

        if ($patientID <= 0 || $diagnosis === '' || $treatmentDone === '') {
            flash('danger', 'Patient, diagnosis, and treatment done are required.');
            redirect_to(page_url('staff_health_record', ['patient' => $patientID]));
        }

        $patient = db_one(
            "SELECT userID FROM tbl_user WHERE userID = ? AND userRole = 'patient' AND status = 'active'",
            [$patientID]
        );
        if (!$patient) {
            flash('danger', 'Patient not found.');
            redirect_to(page_url('staff_health_record'));
        }

        db_execute(
            'INSERT INTO tbl_dental_record
             (userID, appointmentID, toothNumber, diagnosis, treatmentDone, toothCondition, nextAction, dentistNotes, recordedBy)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [
                $patientID,
                $apptID,
                $toothNumber !== '' ? $toothNumber : null,
                $diagnosis,
                $treatmentDone,
                $toothCond,
                $nextAction !== '' ? $nextAction : null,
                $dentistNotes !== '' ? $dentistNotes : null,
                (int) $user['userID'],
            ]
        );

        log_activity('save_dental_record', 'Added dental record for patient #' . $patientID, (int) $user['userID']);
        flash('success', 'Dental record saved successfully.');
        redirect_to(page_url('staff_health_record', ['patient' => $patientID]));
    }

    if ($action === 'update_appointment') {
        require_role(['admin', 'staff']);

        $apptID = (int) ($_POST['appointmentID'] ?? 0);
        $date   = (string) ($_POST['appointmentDate'] ?? '');
        $time   = substr((string) ($_POST['appointmentTime'] ?? ''), 0, 5);
        $status = (string) ($_POST['status'] ?? '');

        $validStatuses = ['pending', 'confirmed', 'completed', 'cancelled'];
        if ($apptID <= 0 || !preg_match('/^\d{4}-\d{2}-\d{2}$/', $date) || !in_array($time, build_time_slots(), true) || !in_array($status, $validStatuses, true)) {
            flash('danger', 'Invalid appointment data.');
            redirect_to(page_url('appointments'));
        }

        $appt = db_one('SELECT * FROM tbl_appointment WHERE appointmentID = ?', [$apptID]);
        if (!$appt) {
            flash('danger', 'Appointment not found.');
            redirect_to(page_url('appointments'));
        }

        db_execute(
            "UPDATE tbl_appointment SET appointmentDate = ?, appointmentTime = ?, status = ?, updatedDate = CURRENT_TIMESTAMP WHERE appointmentID = ?",
            [$date, $time . ':00', $status, $apptID]
        );

        if ($status === 'completed' && (string) $appt['status'] !== 'completed') {
            award_completion_points($appt);
        }

        log_activity('update_appointment', 'Updated appointment #' . $apptID . ' status to ' . $status);
        flash('success', 'Appointment updated.');
        redirect_to(page_url('appointments'));
    }

    if ($action === 'cancel_appointment') {
        $apptID  = (int) ($_POST['appointmentID'] ?? 0);
        if ($apptID <= 0) {
            flash('danger', 'Invalid appointment.');
            redirect_to(page_url('appointments'));
        }

        $isStaff = has_role($user, ['admin', 'staff']);
        $appt = $isStaff
            ? db_one('SELECT * FROM tbl_appointment WHERE appointmentID = ?', [$apptID])
            : db_one('SELECT * FROM tbl_appointment WHERE appointmentID = ? AND userID = ?', [$apptID, (int) $user['userID']]);

        if (!$appt) {
            flash('danger', 'Appointment not found.');
            redirect_to(page_url('appointments'));
        }

        if (!in_array((string) $appt['status'], ['pending', 'confirmed'], true)) {
            flash('danger', 'Only pending or confirmed appointments can be cancelled.');
            redirect_to(page_url('appointments'));
        }

        db_execute(
            "UPDATE tbl_appointment SET status = 'cancelled', updatedDate = CURRENT_TIMESTAMP WHERE appointmentID = ?",
            [$apptID]
        );

        log_activity('cancel_appointment', 'Cancelled appointment #' . $apptID, (int) $user['userID']);
        flash('success', 'Appointment cancelled.');
        redirect_to(page_url('appointments'));
    }

    // No recognised action — do nothing, just redirect cleanly
    redirect_to(page_url('dashboard'));
}

function json_response(array $payload, int $status = 200): void
{
    http_response_code($status);
    header('Content-Type: application/json');
    echo json_encode($payload);
    exit;
}
